#服务器配置
server:
  port: 8080
#Spring配置
spring:
  mail:
    host: smtp.example.com
    port: 587
    username: 3225483474@qq.com
    password: nbghoghtuthlcjff
  data:
    redis:
      host: 117.72.112.62
      port: 6379
      password: 200522
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.112.62:3306/fruit?useSSL=false&serverTimezone=UTC
    username: root
    password: 200522
  devtools:
    restart:
      enabled: true
#Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fruit.entity
  configuration:
    map-underscore-to-camel-case: true
#Logger配置
logging:
  level:
    root: info    # 全局默认日志级别
    com.fruit.mapper: debug  # 特定包的日志级别
    com.baomidou.example.mapper: debug  # 特定包的日志级别
  file:
    name: logs/application.log  # 日志文件路径
#SpringDOC配置
springdoc:
  api-docs:
    enabled: @springdoc.enabled@
  swagger-ui:
    enabled: @springdoc.enabled@
# mybatis开启sql打印配置示例
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

